<?php
	// $Id$

    require_once dirname(__file__) . "/../../themes/vst/config.php";
    
    /**
    * Display help and module information
    * @param path which path of the site we're displaying help
    * @param arg array that holds the current path as would be returned from arg() function
    * @return help text for the path
    */
    function schoolmap_help($path, $arg) 
    {
        $output = ''; 
      
        switch ($path) 
        {
            case ("admin/help#school"):
            $output = '<p>'.  t("Defines an editable school object") .'</p>';
            break;
        }

        return $output;
    }


    /**
    * Valid permissions for this module
    * @return array An array of valid permissions for the onthisdate module
    */
    function schoolmap_perm() 
    {
        return array('administer school content');
    }


    /**
    * Removes non-alphanumeric characters from the string (for doing javascript)
    * @return string 
    */
    function schoolmap_cleanstr($str)
    {
        return preg_replace("/[^\w]/", "", $str);
    }
    
    
    /**
    * Implementation of hook_block().
    * @param string $op one of "list", "view", "save" and "configure"
    * @param integer $delta code to identify the block
    * @param array $edit only for "save" operation
    */
    function schoolmap_block($op = 'list', $delta = 0, $edit = array()) 
    {
        global $base_path;

        $block = array();
        
        switch ($op)
        {
            case ("list"):
            {
                $block[0]["info"] = t("School");
                break;
            }
            
            case ("view"):
            {
                $schools = array();
                
                $block["subject"] = "";  
                $block["content"] = '
                    <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyDH6jMV0_4Fu5hZ6ydfXooyfILqyJz6a9s&sensor=false"></script>
                    <script type="text/javascript" src="' . $base_path . 'sites/all/modules/schoolmap/map.js"></script>
                    <script type="text/javascript">

                        var schools = new Object;
                        var map = null;
                ';
                
                $query = "SELECT f.filepath as picture, r.body, n.title, s.field_teaser_value as teaser, s.field_name_value as name, s.field_point_value as point, s.field_status_value as status FROM {node} n LEFT JOIN {node_revisions} r on n.nid = r.nid and n.vid = r.vid LEFT JOIN {content_type_school} s ON n.nid = s.nid LEFT JOIN files f on s.field_picture_fid = f.fid WHERE n.status = 1 AND n.type = 'school' ORDER BY status ASC, (s.field_order_value + 0) ASC";
                $query_result =  db_query($query);
                
                while($s = db_fetch_object($query_result))
                {
                    $schools[] = $s;

                    $properties = "";
                    foreach ($s as $prop => $value)
                    {
                        if ($prop != "point" && $prop != "body")
                            $properties .= $prop . " : \"" . str_replace("\"", "\\\"", $value) . "\", ";
                    }
                    $properties = rtrim($properties, ", ");    
                    
                    $block["content"] .= "    schools[\"" . schoolmap_cleanstr($s->name) . "\"] = new school({ point : " . (!empty($s->point) ? '[' . $s->point . ']' : 'null') . ", " . $properties . " } );\n";
                }
        
                $block["content"] .= '

                        $(function() {
                            map = new interactiveMap(
                                schools, 
                                document.getElementById("map"), 
                                {
                                    zoom: 6,
                                    center: { 
                                        // Most of Tanzania and Malawi visible
                                        lat: -9.664608, 
                                        lng: 34.804688
                                    },
                                    type: "TERRAIN"
                                }
                            );
                        });

                    </script>
                
                    <div id="schoolslist">';
                
                $c = 0;
                while (1)
                {
                    $status = $schools[$c]->status;
                
                    $block["content"] .=  "<h1>" . $status . "</h1><ol start=\"" . ($c + 1) . "\">";
                
                    do
                    {
                        $block["content"] .=  "<li>" . 
                                                (strlen($schools[$c]->point) > 0 ? "<a href=\"javascript:map.openInfoWindow('" . schoolmap_cleanstr($schools[$c]->name) . "');\">" . ucfirst($schools[$c]->name) . "</a>" : ucfirst($schools[$c]->name)) . 
                                                (strlen($schools[$c]->body) > 0 ? "&nbsp;&nbsp;<a class=\"discrete\" href=\"" . $variables["root_url"] . "schools/" . schoolmap_cleanstr($schools[$c]->name) . "\">more &raquo;</a>" : "") . 
                                              "</li>";
                        $c ++;
                    }
                    while (isset($schools[$c]) && strtolower($status) == strtolower($schools[$c]->status));
                
                    $block["content"] .=  "</ol>";
                
                    if (!isset($schools[$c]))
                        break;
                }
                
                $block["content"] .= "</div><div id=\"map\" style=\"width: 590px; height:550px\"></div>";

                break;
            }
        }  

        return $block;
    }